### ISSUE TITLE
0.3.0 regression test failure

### ISSUE THREAD

**Issue by chenrui333** [flosse/sloc#137]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
  ==> /opt/homebrew/Cellar/sloc/0.3.0/bin/sloc --format=csv .
  /opt/homebrew/Cellar/sloc/0.3.0/libexec/lib/node_modules/sloc/node_modules/readdirp/index.js:264
      throw new TypeError('readdirp: root argument must be a string. Usage: readdirp(root, options)');
      ^
  
  TypeError: readdirp: root argument must be a string. Usage: readdirp(root, options)
      at readdirp (/opt/homebrew/Cellar/sloc/0.3.0/libexec/lib/node_modules/sloc/node_modules/readdirp/index.js:264:11)
      at readDir (/opt/homebrew/Cellar/sloc/0.3.0/libexec/lib/node_modules/sloc/lib/cli.js:176:12)
      at /opt/homebrew/Cellar/sloc/0.3.0/libexec/lib/node_modules/sloc/lib/cli.js:194:16
      at FSReqCallback.oncomplete (node:fs:200:5)
  
  Node.js v20.7.0
  
  Error: sloc: failed
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/6256768201/job/16988130801
relates to Homebrew/homebrew-core#144381

**Comment by chenrui333** [comment]
Any update on this thread?

**Comment by domengasperlin** [comment]
The issues will be gone if toggling release flow on master after https://github.com/flosse/sloc/pull/144
@flosse can you toggle another release or include new changes in 0.3.1:

**Comment by domengasperlin** [comment]
@flosse any updates on it 🤞

**Comment by domengasperlin** [comment]
Hey, @chenrui333 release was toggled on main branch, tests show now pass https://github.com/flosse/sloc/pull/144#issuecomment-1874109795

**Comment by flosse** [comment]
Can we close this? Please test v0.3.2 :pray:

**Comment by domengasperlin** [comment]
We can its already deployed on brew https://github.com/Homebrew/homebrew-core/pull/161955/files
