### ISSUE TITLE
alias not working

### ISSUE THREAD

**Issue by hampsterx** [flosse/sloc#56]
eg 

```javascript
sloc --alias jsx=js 
```

looks like its doing readdirp with fileFilter set to list of exts but this does not include any alias so it's filtering them out before it can do the stats on it :(

**Comment by flosse** [comment]
thx for reporting that issue!

**Comment by flosse** [comment]
I just had a short look at the current source and saw that James Tatum already fix it in 7eec61ed :)
If you like, you can fix a blocking bug so we can release a next version that contains that fix.
