### ISSUE TITLE
TODO Count?

### ISSUE THREAD

**Issue by jgodi** [flosse/sloc#68]
Could it be possible to add a TODO count? Just to check how many `#TODO`'s developers sprinkled inside the code?

**Comment by flosse** [comment]
> Could it be possible to add a TODO count? Just to check how many #TODO's developers sprinkled inside the code?

Of course. If you have a solution, go ahead :)

**Comment by jzarob** [comment]
I created pull request #82 to resolve this issue as it was something that I also ran into.

**Comment by flosse** [comment]
To close this we should mention it in the changelog and readme.

**Comment by jzarob** [comment]
I included a change in the README already
