### ISSUE TITLE
[Feature request] Allow multiple files/directories

### ISSUE THREAD

**Issue by Phr33d0m** [flosse/sloc#70]
Hello, it'd be nice to be able to supply the cli more than one file/directory (as in trying to count a Laravel project one's own sloc):

```
$ sloc app/Http/ app/Console/Commands/ app/Events/ app/Exceptions/ app/Helpers/ app/Models/ app/Policies/ resources/assets/js/ resources/assets/sass/ resources/lang/ resources/views/
```

That way we can get a more precise output excluding vendor provided libraries.

Regards.

**Comment by flosse** [comment]
Feel free to hack it an create a PR :)
