### ISSUE TITLE
support f#

### ISSUE THREAD

**Issue by isamuelson** [flosse/sloc#76]

**Comment by flosse** [comment]
feel free to create PR ;-)

**Comment by jpaulin** [comment]
If the F# syntax regarding source code comments is as simple as this:
1) single-line comments start with double forward slash (ie. // )
2) multi-line comments are marked with a pair of (* and *) 

then it should be quite straightforward to add support. 

Can you comment on this? I have zero experience with coding F# but checked the FAQ for the language.  
@isamuelson
